### ISSUE TITLE
Error message in 'Eval Error' in spite of proper output

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/htmlifier#111]
Hi! Hope u r doing well. I am back again with some conversations.

I had made the [EvalJS](https://sparkscratch-p.github.io/EvalJS/) with the `eval` variable features of this HTMLifier. It is working well with all features, quite properly. Unfortunately, there is a bit of **_Glitch faced in the` eval error `cloud var._**

You can try the mistake out. There, start it with **Enter + N** and then, type `alert("Hi!");`, then to end coding, type, `cde end` and then press **Enter + R** to Run. It will show the proper pop-up, but after that, on the next screen, it shows _Error:_ `Unexpected token 'if'`. But, practically, there was no error.

**Comment by SheepTester** [comment]
This is what you set `☁ eval` to

![image](https://user-images.githubusercontent.com/22133785/128902453-60ae9c52-dadf-405b-8176-d51d2399c23a.png)

```js
OUTPUT: (None, if the next line is blank) 6 ERROR !!! (None, if the next line is blank) SyntaxError: Unexpected token 'if'
```

This is not valid JavaScript. You have a label `OUTPUT`, then enclosed in parentheses a comma expression. However, the right side of the comma operator has the keyword `if`, which can only be used in a statement rather than an expression

![image](https://user-images.githubusercontent.com/22133785/128902621-bc756b96-f27b-4ab9-becd-2c70c4c94da0.png)

This is a bug with your project, not the HTMLifier. Practically, there was actual;y an error. Make sure you check what `☁ eval` is being set to.

**Comment by SparkScratch-P** [comment]
Oh! Thanks for your help bro.... I will keep it in mind from the next time.
Sorry for disturbing you.
[image: GeoTrack]
<https://geotrack.email/?utm_source=gmail&utm_medium=signature&utm_campaign=viralSignature>
Sender
notified with GeoTrack
<https://geotrack.email/?utm_source=gmail&utm_medium=signature&utm_campaign=viralSignature>
[image: 2]

**Comment by SheepTester** [comment]
Worrying, your emails have trackers

**Comment by SparkScratch-P** [comment]
Yes, I use geo-track, unlicensed, can't track location, but can see if they
are read or not.. for Github issues, it does not track if the mails are
read or nt. so, not useful fo gi issues
[image: GeoTrack]
<https://geotrack.email/?utm_source=gmail&utm_medium=signature&utm_campaign=viralSignature>
Sender
notified with GeoTrack
<https://geotrack.email/?utm_source=gmail&utm_medium=signature&utm_campaign=viralSignature>
