### ISSUE TITLE
If Tried to Output a ZIP File So The Preview doesn't works

### ISSUE THREAD

**Issue by e-coders** [SheepTester/htmlifier#115]
If Tried to Output a ZIP File So The Preview doesn't works
Idea: Try Previewing the Index.html file of ZIP File to work it online!

**Comment by SheepTester** [comment]
I think instead, it should remove the preview button when downloading as a zip since the zip file can't be previewed in the web page without some service worker magic (which wouldn't work in the offline edition) or modifying the zip file (which would ruin the point of previewing it).

If you want to preview the result, make it output an HTML file instead and click the preview button

**Comment by e-coders** [comment]
ok
