### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by TermitCG** [SheepTester/htmlifier#43]
Project doesn't load. I waited 10 minutes and still nothing.

**Comment by SheepTester** [comment]
Are there any errors in the inspect element console?

**Comment by TermitCG** [comment]
yes. Errors:
`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. <URL>
index.html:1 Access to XMLHttpRequest at 'file:///D:/Download/proj%20(2)/project.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
project.json:1 Failed to load resource: net::ERR_FAILED
index.html:904 Uncaught (in promise) TypeError: Cannot read property 'data' of null
    at file:///D:/Download/proj%20(2)/index.html:904:71`

**Comment by SheepTester** [comment]
Ah, it seems like you downloaded the HTMLified project as a .zip and opened the file as a file:// URL. Unfortunately, this won't work because your browser prevents websites, even local HTML files, from accessing other files on your computer, like the project.json.

You can host a web server locally instead, such as using [http-server](https://www.npmjs.com/package/http-server), or host the files on a web host like [Github Pages](https://pages.github.com/)
