### ISSUE TITLE
What kind of JS code Runs in Eval var?

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/htmlifier#91]
### What kind of JS code Runs in Eval var?

 Does it run single-line codes with answers in just letters and numbers?
 Can u please give some examples?

**Thank You**

**Comment by SheepTester** [comment]
All JS code should work; JavaScript isn't very whitespace sensitive so you can put multiple statements in one line if you put newlines in between

For example, this will make it so that when you click anywhere, it'll ask the user for text and then alert it if the user didn't cancel:

```js
set [☁ eval v] to [document.addEventListener('click', e => { const input = prompt('What to say?'); if (input !== null) alert(input) })]
```

![image](https://user-images.githubusercontent.com/22133785/118203571-2ef23100-b411-11eb-8bb2-c7fdc2935276.png)

**Comment by SparkScratch-P** [comment]
Ummm.. Thanks, but then, will it be able to make a project with an algo as follows, as simple as that?

```
Ask [ enter a JS code]
set ☁ eval v to (answer) 
Show variable [ ☁ eval output]

```
... such that `☁ eval output v` will contain the results of a JS code?

If yes, pls can u give a gist about what sort of codes can be put?

**Comment by SheepTester** [comment]
Yes, that'll work. You can put any JS code; just look up JS code samples online

**Comment by SparkScratch-P** [comment]
## Yeah!!! Thanks again.
 Any JS code will run? Or only the ones that go with `eval() `function? 

Will there be any such risks: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval! ???

☺

**Comment by SparkScratch-P** [comment]
Codes that have only texts as well as their results should also only be in string , will be able to run? Am I correct?
 Please help me out 😅

**Comment by SparkScratch-P** [comment]
Codes that have only texts as well as their results should also only be in string , will be able to run? Am I correct?
 Please help me out 😅

**Comment by SheepTester** [comment]
> Any JS code will run? Or only the ones that go with `eval() `function?

Any JavaScript code can go inside `eval()` (except for `import`/`export` statements since they need to be in a module context)

> Will there be any such risks: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval! ???

Since you're running JavaScript, it can do anything a web page can do, such as access the cookies on the website it's hosted on. With great power comes great responsibility.

> Codes that have only texts as well as their results should also only be in string , will be able to run? Am I correct?
> Please help me out 😅

Yes, though I think return values of numbers and booleans are also allowed

**Comment by SparkScratch-P** [comment]
### Thanks bro! 
 *Hope u don't mind addressing u 'bro'. U r of my sis's age. 

```
With great power comes great responsibility.
```
Hmm... U have given me the power And I wish to use it with responsibility :))

## HTMLifier is the best !!!!!!

**Comment by SparkScratch-P** [comment]
Ummm... I have tried to make one, can u pls say, if it's working properly? Can u also please check that the whole of starting _Control DIrectory_ instructions r correct or not? I actually don't have a proper idea about how it should work.

**Thanks in Advance**

The following link contains the project as **HTML**:
https://drive.google.com/file/d/1iHU438jZPsauzZj6tCzf_2fQ6hPusTAn/view?usp=sharing
